### ISSUE TITLE
Object field selector not working

### ISSUE THREAD

**Issue by mspiegel** [zorba-processor/zorba#7]
```
$ zorba -v
Zorba NoSQL Query Processor, Version: 3.1.0
$ zorba -q '{"foo":"bar"}.foo'
(no URI):1,15: static error [err:XPST0003]: invalid expression: syntax error,
unexpected expression (missing comma "," between expressions?)
```

**Comment by ghislainfourny** [comment]
Hi Michael,

Zorba supports two parsers: JSONiq (more pleasant for JSON data), and XQuery (more pleasant for XML data). The default parser is XQuery. The differences are documented [on this page](http://www.zorba.io/documentation/latest/zorba/xml_json).

In order to activate the JSONiq parser, you need to use the JSONiq header (jsoniq version "1.0";)before your query:

    zorba -q 'jsoniq version "1.0"; {"foo":"bar"}.foo'

For completeness: object lookup is also possible with the XQuery parser, however the syntax is that of a function call:

    zorba -q '{"foo":"bar"}("foo")'

**Comment by mspiegel** [comment]
Oops now I see this documented on the link provided and I also see it on https://github.com/ghislainfourny/jsoniq-tutorial. Thank you!
